# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import sensor_pb2 as proto_dot_sensor__pb2


class sensorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.pushValue = channel.unary_unary(
                '/sensor.sensor/pushValue',
                request_serializer=proto_dot_sensor__pb2.sensorValue.SerializeToString,
                response_deserializer=proto_dot_sensor__pb2.Null.FromString,
                )
        self.pushValues = channel.stream_unary(
                '/sensor.sensor/pushValues',
                request_serializer=proto_dot_sensor__pb2.sensorValue.SerializeToString,
                response_deserializer=proto_dot_sensor__pb2.Null.FromString,
                )


class sensorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def pushValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def pushValues(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_sensorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'pushValue': grpc.unary_unary_rpc_method_handler(
                    servicer.pushValue,
                    request_deserializer=proto_dot_sensor__pb2.sensorValue.FromString,
                    response_serializer=proto_dot_sensor__pb2.Null.SerializeToString,
            ),
            'pushValues': grpc.stream_unary_rpc_method_handler(
                    servicer.pushValues,
                    request_deserializer=proto_dot_sensor__pb2.sensorValue.FromString,
                    response_serializer=proto_dot_sensor__pb2.Null.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sensor.sensor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class sensor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def pushValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sensor.sensor/pushValue',
            proto_dot_sensor__pb2.sensorValue.SerializeToString,
            proto_dot_sensor__pb2.Null.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def pushValues(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/sensor.sensor/pushValues',
            proto_dot_sensor__pb2.sensorValue.SerializeToString,
            proto_dot_sensor__pb2.Null.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
